# Generated by Django 3.2.6 on 2021-08-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
