# Generated by Django 3.2.6 on 2021-08-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
