# Generated by Django 3.2.6 on 2021-08-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_postmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='logo',
        ),
    ]
