# Generated by Django 3.2.6 on 2021-08-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_postmodel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='logo',
            field=models.ImageField(default=1, upload_to='images/posty'),
            preserve_default=False,
        ),
    ]
